$axure.loadCurrentPage({
  "url":"админ__панель_администратора.html",
  "generationDate":new Date(1393265791808.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"IsRegistred"],
  "page":{
    "packageId":"a45274ec9a9c417ea84ee7052c1c5e40",
    "type":"Axure:Page",
    "name":"Админ. панель администратора",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"31c307833e7645eb8f52c20b04dacc1b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":974}},
          "adaptiveStyles":{
},
          "masterId":"18f5f2c19e63498db99061699d0d00d5"},
{
          "id":"de515e0a24434c65b9ba9416d2dbc98d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":210},
            "size":{
              "width":180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/админ_панель_участника/u35_line.png"}},
{
          "id":"0a16281b9dbc4f9a9bf47abb247e4c3f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":300},
            "size":{
              "width":180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/админ_панель_участника/u35_line.png"}},
{
          "id":"62a9ad59a1024d96bdc528eddf9f72a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":120},
            "size":{
              "width":760,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b005d1f7fe14ec08ef3e8507744fbf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":120},
                "size":{
                  "width":760,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/админ_панель_участника/u46.png"}},
{
          "id":"0265dd46ab0f4acfa2805e5c0dbb257b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"bf2c78cd6b5a4a098aa3632283b58004"},
{
          "id":"a8594456e9c5468f8912de1ac2f1b1aa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":150},
            "size":{
              "width":760,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/админ_панель_участника/u84_line.png"}},
{
          "id":"46000bfdebbf400d8fc5482185655293",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":492.5,
              "y":122},
            "size":{
              "width":255,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3630c3c74bbd46279cc727551a627527",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":492.5,
                  "y":122},
                "size":{
                  "width":255,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d7eaadd348f4dd9b3370927e7e0ac8b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":155},
            "size":{
              "width":10,
              "height":565}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/админ_панель_участника/u87_line.png"}},
{
          "id":"f48bf3d825944702883ec0cc0dd6d7ba",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":155},
            "size":{
              "width":10,
              "height":565}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/админ_панель_участника/u87_line.png"}},
{
          "id":"cec374e24c974981a7c1b987a1c64e12",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":190},
            "size":{
              "width":760,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/админ_панель_участника/u84_line.png"}},
{
          "id":"26d3acec33414e898e23e61b1d44ad03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":295,
              "y":168},
            "size":{
              "width":42,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae136b4aae4a422dadb371321208283d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":295,
                  "y":168},
                "size":{
                  "width":42,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"059a5c05b5ab410497f81f6c98a3c1a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":472,
              "y":168},
            "size":{
              "width":57,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03929fe99d744c8598f9948b5de8cdc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":472,
                  "y":168},
                "size":{
                  "width":57,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4df8831edc44b8690cee6a89c2befcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":854,
              "y":168},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72c0cdba90a34e73accd7971551c33e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":854,
                  "y":168},
                "size":{
                  "width":80,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2f70723a56a411f8047ebe5bab5ca82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":257},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1eeb1e33a345418082677899ff20a7fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":257},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8757d2f4676549d196e480578740b0e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":255},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d6d48d8fc4c42f2ae4e3a0d87b0fde2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":255},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2de481f096744e6a867207c66ec0215c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":781,
              "y":250},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Подтверждение внесения MyCrypt in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"подтверждение_внесения_mycrypt.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e5e21a46cddf4c698a753c2ab3117411",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":893,
              "y":250},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Отклонить внесение MyCrypt in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"отклонить_внесение_mycrypt.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d94054663f894c4d8bd34ea5af1e2124",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":649,
              "y":168},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f2309a8f97d46f6bafe793fbe295b0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":649,
                  "y":168},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cafeb2897b84492bb41755af3bf38e63",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":155},
            "size":{
              "width":10,
              "height":565}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/админ_панель_участника/u87_line.png"}},
{
          "id":"2c883982030e49c99daa69ee9203e090",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":634,
              "y":255},
            "size":{
              "width":102,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79c0626e572d47d9b58b99b4930878e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":634,
                  "y":255},
                "size":{
                  "width":102,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16c6a193af4c4565b8fc3e9e97eba638",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":337},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed3f6508e3d84f90a5096e33509ddfb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":337},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15eb0227eb534e87a432ca9bd5f16c40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":335},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"368ca48ed8a748f0b13902beca2141cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":335},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e50385383fb49c1bd39f6d5ab97a1c1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":781,
              "y":330},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Подтвердить снятие средств in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"подтвердить_снятие_средств.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"def7bb152f6f4d32ba61367501f60ca1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":893,
              "y":330},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Отклонить снятие средств in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"отклонить_снятие_средств.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1d8a155bc29641f88bff23ccb5c396f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":634,
              "y":335},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f95eaa291442499eb2ffc6e810a7f96d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":634,
                  "y":335},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b4424e1d3b445e394f41c1df50dfa84",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"b5d7cf91a6eb42ecbf1400ed7d82449c"}]}},
  "masters":{
    "18f5f2c19e63498db99061699d0d00d5":{
      "packageId":"18f5f2c19e63498db99061699d0d00d5",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a8159063e477466e9fbce07355c5e82a",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":30,
                "y":994},
              "size":{
                "width":100,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"14084ae3f8f8479588a4eb0d87987a24",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":30,
                    "y":994},
                  "size":{
                    "width":100,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u1.png"}},
{
            "id":"402b7d65930e42c8ab2b58703829c3ff",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":974},
              "size":{
                "width":920,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF999999}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/главная/u3_line.png"}},
{
            "id":"8ad1a3f0f46946ed954c921a048a927a",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":232,
                "y":994},
              "size":{
                "width":100,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"045f645385594381bc81c84af8d10830",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":232,
                    "y":994},
                  "size":{
                    "width":100,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u1.png"}},
{
            "id":"4f46ba15deff4634beb81ce43f2ac724",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":440,
                "y":994},
              "size":{
                "width":100,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8fbf82e26ca642d49cb090ebc8bcf612",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":440,
                    "y":994},
                  "size":{
                    "width":100,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u1.png"}},
{
            "id":"6d3c901a6f17447093f7170463b3d62f",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":670,
                "y":994},
              "size":{
                "width":100,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0421c61f4a634d8bb20bd46d208e517c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":670,
                    "y":994},
                  "size":{
                    "width":100,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u1.png"}},
{
            "id":"887fd71470d44bfaa854cdb2fa05b565",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":900,
                "y":994},
              "size":{
                "width":100,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f3ab24dd2c0e4dc2bf2496df9596c924",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":900,
                    "y":994},
                  "size":{
                    "width":100,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u1.png"}},
{
            "id":"427256a81d85467994b76439cebc69ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":44,
                "y":1094},
              "size":{
                "width":72,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6931673c584c49f6975614fa7e02d39d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":44,
                    "y":1094},
                  "size":{
                    "width":72,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1d6d6f7c2ec84f3893bf64c4d3fcb99c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":254,
                "y":1094},
              "size":{
                "width":56,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"85395471d60a476b83ec4368b18b85ea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":254,
                    "y":1094},
                  "size":{
                    "width":56,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"286ebe8d7e7a4fe48a4253e08f63871e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":444,
                "y":1094},
              "size":{
                "width":93,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a5014b69e8784418a9f156e60602cebf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":444,
                    "y":1094},
                  "size":{
                    "width":93,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3e53a03a52bb4e1dab7eadf87174205f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":706,
                "y":1094},
              "size":{
                "width":27,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"677f9235f89546e6b497a67782fd35cd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":706,
                    "y":1094},
                  "size":{
                    "width":27,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5c250de23dc04c7992b97239bee7693e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "location":{
                "x":894,
                "y":1094},
              "size":{
                "width":111,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"85e31ddecc0540968f0183d5ce0e04a0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "location":{
                    "x":894,
                    "y":1094},
                  "size":{
                    "width":111,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f81a839fa3ec462f9d07447cb7d5ea94",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":1013},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"09022a734e2d4cf9affff1988afcb311",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":1013},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u22.png"}},
{
            "id":"a2f3a6dc6b8a4ffd93187d27b302bb68",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":257,
                "y":1014},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fc37cbff9aec48eaa002a4a4c3715274",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":257,
                    "y":1014},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u22.png"}},
{
            "id":"160169868a5041da9050a8dc8f4f02d1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":465,
                "y":1014},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"61d1fb7bf72d454c88b0d1c29ed72de4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":465,
                    "y":1014},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u22.png"}},
{
            "id":"effa31e5f1764b8d8abdeef0bc7e3e61",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":695,
                "y":1014},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1a3841491b4e4deab50f395a461f622f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":695,
                    "y":1014},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u22.png"}},
{
            "id":"6184d0914218429d831029072917da31",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":925,
                "y":1014},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a570c4bf1e0a4ddcb13ae8cf8add5552",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":925,
                    "y":1014},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u22.png"}}]}},
    "bf2c78cd6b5a4a098aa3632283b58004":{
      "packageId":"bf2c78cd6b5a4a098aa3632283b58004",
      "type":"Axure:Master",
      "name":"Навигация по админке администратора",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"71b1b9b974134a54a48c7eea3e9a7b5e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":120},
              "size":{
                "width":180,
                "height":380}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c98c4e1f42b349878fed7662313b23fc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":120},
                  "size":{
                    "width":180,
                    "height":380}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/админ__панель_администратора/u37.png"}},
{
            "id":"67f741985f78439b8bbdee033141be15",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "horizontalAlignment":"center",
              "location":{
                "x":58,
                "y":136},
              "size":{
                "width":110,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"14e95f72b7694b508ce5ae0298078d9a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "horizontalAlignment":"center",
                  "location":{
                    "x":58,
                    "y":136},
                  "size":{
                    "width":110,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Админ. панель администратора in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"админ__панель_администратора.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2a1a47c0df9e4de38762ba3c9d06e9ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "horizontalAlignment":"center",
              "location":{
                "x":42,
                "y":233},
              "size":{
                "width":140,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"20f09b4d617041aabfe01cd4d58309c4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "horizontalAlignment":"center",
                  "location":{
                    "x":42,
                    "y":233},
                  "size":{
                    "width":140,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open АПМ | Редактирование пользователей in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"апм___редактирование_пользователей.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2d0d2c4ff18d4780b7945a341bb96cde",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "horizontalAlignment":"center",
              "location":{
                "x":56,
                "y":336},
              "size":{
                "width":107,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ef5f1707be2344a69d13c8738a3bebc2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "horizontalAlignment":"center",
                  "location":{
                    "x":56,
                    "y":336},
                  "size":{
                    "width":107,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Размещение новостей in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"размещение_новостей.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"855ae197207143bd96db215b131e460f",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":197},
              "size":{
                "width":180,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/админ_панель_участника/u35_line.png"}},
{
            "id":"8544e519cdb940c78c851080d7abbb93",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":19.5,
                "y":300},
              "size":{
                "width":180,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/админ_панель_участника/u35_line.png"}},
{
            "id":"714650cc2758420dac5fd70b7b9a1a3c",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":400},
              "size":{
                "width":180,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/админ_панель_участника/u35_line.png"}},
{
            "id":"4e0febc63ac3463db7bfac48ac5afe94",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "horizontalAlignment":"center",
              "location":{
                "x":22,
                "y":421},
              "size":{
                "width":176,
                "height":66}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"88fcdb9596d944a8b9ae9b402e0e7ebb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "horizontalAlignment":"center",
                  "location":{
                    "x":22,
                    "y":421},
                  "size":{
                    "width":176,
                    "height":66}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Ввод и изменение параметров системы in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"ввод_и_изменение_параметров_системы.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "b5d7cf91a6eb42ecbf1400ed7d82449c":{
      "packageId":"b5d7cf91a6eb42ecbf1400ed7d82449c",
      "type":"Axure:Master",
      "name":"Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e08c2a7d5878465d8431a3e82ac01d11",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":460,
                "y":10},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6bf81276138145e4a69d32f79ad6e41a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":460,
                    "y":10},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u104.png"}},
{
            "id":"5d65676a59cb4c27b2affd3dd530a65c",
            "label":"Вход | Регистрация",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":700,
                "y":10},
              "size":{
                "width":310,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onLoad":{
                "description":"OnLoad",
                "cases":[{
                    "description":"Case 1<br> (If value of IsRegistred equals &quot;true&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"IsRegistred"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"true",
                        "stos":[]}},
                    "actions":[{
                        "action":"setPanelState",
                        "description":"Set Вход | Регистрация to Информация о пользователе",
                        "panelsToStates":[{
                            "panelPath":["5d65676a59cb4c27b2affd3dd530a65c"],
                            "stateInfo":{
                              "setStateType":"diagram",
                              "stateNumber":2,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":false,
                              "showWhenSet":false,
                              "options":{
                                "compress":false}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"1e672d456b8741f39fa27106b1beb640",
                "label":"Вход | Регистрация",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"57140586a7ee4b43aa3a6692a99c8594",
                    "label":"",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":310,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f662fbd30ce8436cb40cb7ae8cc14011",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":310,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/главная/u107.png"}},
{
                    "id":"bd8018d9401b41d7b27ca97c96fded4c",
                    "label":"",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"verticalLine",
                    "styleType":"verticalLine",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":95,
                        "y":0},
                      "size":{
                        "width":10,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "images":{
                      "start~":"resources/images/transparent.gif",
                      "end~":"resources/images/transparent.gif",
                      "line~":"images/главная/u109_line.png"}},
{
                    "id":"0f3e0bd7dd12496eb31b35833006f39c",
                    "label":"",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"28px",
                      "location":{
                        "x":15,
                        "y":8},
                      "size":{
                        "width":63,
                        "height":33}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"cc1f87e161d84506816c03e29c7b764c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"28px",
                          "location":{
                            "x":15,
                            "y":8},
                          "size":{
                            "width":63,
                            "height":33}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"fadeWidget",
                                "description":"Toggle Форма входа",
                                "objectsToFades":[{
                                    "objectPath":["e25359213d124160aa87ca25b79b9286"],
                                    "fadeInfo":{
                                      "fadeType":"toggle",
                                      "options":{
                                        "showType":"none"}}}]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"9b18b1aed72a4283aa89bc3289c656d5",
                    "label":"",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":125,
                        "y":7},
                      "size":{
                        "width":10,
                        "height":10}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Регистрация in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"регистрация.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "scrollbars":"none",
                    "fitToContent":true,
                    "propagate":false,
                    "diagrams":[{
                        "id":"73fbc92942b5422d88338fa50da0191c",
                        "label":"State1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"3fbb36f21ade491ab9eb2882d63cf415",
                            "label":"Перейти в регистрацию",
                            "parentDynamicPanel":"9b18b1aed72a4283aa89bc3289c656d5",
                            "type":"dynamicPanel",
                            "styleType":"dynamicPanel",
                            "visible":true,
                            "style":{
                              "size":{
                                "width":10,
                                "height":10}},
                            "adaptiveStyles":{
},
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"Open Регистрация in Current Window",
                                        "target":{
                                          "targetType":"page",
                                          "url":"регистрация.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "scrollbars":"none",
                            "fitToContent":true,
                            "propagate":false,
                            "diagrams":[{
                                "id":"ad4c92a6f0e147b2b4d82106bd45adfb",
                                "label":"State1",
                                "type":"Axure:PanelDiagram",
                                "objects":[{
                                    "id":"f8dc6c145c2f41f4aa942b82cdc964f9",
                                    "label":"",
                                    "parentDynamicPanel":"3fbb36f21ade491ab9eb2882d63cf415",
                                    "type":"buttonShape",
                                    "styleType":"paragraph",
                                    "visible":true,
                                    "style":{
                                      "fontSize":"28px",
                                      "size":{
                                        "width":170,
                                        "height":40}},
                                    "adaptiveStyles":{
},
                                    "objects":[{
                                        "id":"f207725a28ac4c3f9be5a2ba54a67d41",
                                        "label":"",
                                        "isContained":true,
                                        "parentDynamicPanel":"3fbb36f21ade491ab9eb2882d63cf415",
                                        "type":"richTextPanel",
                                        "styleType":"paragraph",
                                        "visible":true,
                                        "style":{
                                          "fontSize":"28px",
                                          "size":{
                                            "width":170,
                                            "height":40}},
                                        "adaptiveStyles":{
}}],
                                    "images":{
                                      "normal~":"resources/images/transparent.gif"}}]}]}]}]},
{
                    "id":"e25359213d124160aa87ca25b79b9286",
                    "label":"Форма входа",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":false,
                    "style":{
                      "location":{
                        "x":0,
                        "y":70},
                      "size":{
                        "width":10,
                        "height":10},
                      "visible":false},
                    "adaptiveStyles":{
},
                    "scrollbars":"none",
                    "fitToContent":true,
                    "propagate":false,
                    "diagrams":[{
                        "id":"6f7b56455f3c40d4bf33b8fabc998f48",
                        "label":"State1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"c9cd99cd79924d75826942ea76870e31",
                            "label":"",
                            "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                            "type":"buttonShape",
                            "styleType":"buttonShape",
                            "visible":true,
                            "style":{
                              "size":{
                                "width":310,
                                "height":150}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"26709191915e427bb77a5de4707d0a5c",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "size":{
                                    "width":310,
                                    "height":150}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"images/главная/u117.png"}},
{
                            "id":"47334483f651417bb65616b5431c73f7",
                            "label":"",
                            "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                            "type":"textBox",
                            "styleType":"textBox",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":15,
                                "y":20},
                              "size":{
                                "width":275,
                                "height":25}},
                            "adaptiveStyles":{
}},
{
                            "id":"c1d9d316058442a1bf306cb63481d033",
                            "label":"",
                            "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                            "type":"textBox",
                            "styleType":"textBox",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":15,
                                "y":70},
                              "size":{
                                "width":275,
                                "height":25}},
                            "adaptiveStyles":{
}},
{
                            "id":"b69a917f5ecd4416a193b64512c4cee4",
                            "label":"",
                            "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":24,
                                "y":23},
                              "size":{
                                "width":36,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"74127ee343cd4002ba47363614659620",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "location":{
                                    "x":24,
                                    "y":23},
                                  "size":{
                                    "width":36,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"482e38d110eb4855afc10e82db94eaae",
                            "label":"",
                            "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":24,
                                "y":74},
                              "size":{
                                "width":45,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"672c1a628ac5438db7e3e34dd57798af",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "location":{
                                    "x":24,
                                    "y":74},
                                  "size":{
                                    "width":45,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"4075f77a503941b998eb5a49a505f1ef",
                            "label":"",
                            "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                            "type":"button",
                            "styleType":"button",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":190,
                                "y":115},
                              "size":{
                                "width":100,
                                "height":25}},
                            "adaptiveStyles":{
},
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"Open Админ панель участника in Current Window",
                                        "target":{
                                          "targetType":"page",
                                          "url":"админ_панель_участника.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true}]}]}]},
{
                "id":"7751348731ea43fda9d7a4cf751ff4e0",
                "label":"Информация о пользователе",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b8b7eb3c9cf24ddca53af376039eda8c",
                    "label":"",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":310,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c1e0c1209227463d99b493e36858dbcd",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":310,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/главная/u107.png"}},
{
                    "id":"f3dfa111fd5c4c1fb51c2e512c6aaa14",
                    "label":"",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "location":{
                        "x":41,
                        "y":13},
                      "size":{
                        "width":228,
                        "height":24}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"97d1433241e64671918bf24e66165869",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "location":{
                            "x":41,
                            "y":13},
                          "size":{
                            "width":228,
                            "height":24}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]},
{
            "id":"da40d25c119b42dda5bb2ea76ad449a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "location":{
                "x":522,
                "y":18},
              "size":{
                "width":57,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2927063ec1074054b80daabb05653b43",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "location":{
                    "x":522,
                    "y":18},
                  "size":{
                    "width":57,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e327dd1eef584794bcae0e0226f4263c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":232,
                "y":10},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a4a0459e97374e1ea41e6b02e0cf2871",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":232,
                    "y":10},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u104.png"}},
{
            "id":"b8dacec1e6b94fc8b0692c021db18514",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "location":{
                "x":278,
                "y":18},
              "size":{
                "width":75,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c76cfd1b69574f54b1bab98c9fdbe226",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "location":{
                    "x":278,
                    "y":18},
                  "size":{
                    "width":75,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"eb41e6fa90554a9ba2a98f3cf8459eb9",
            "label":"Перейти на главную",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":10},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Главная in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"главная.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"db15717b5e48406fbe54dbd6dc532258",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"0f3335600b4d4e0f868bc4627d53f23b",
                    "label":"",
                    "parentDynamicPanel":"eb41e6fa90554a9ba2a98f3cf8459eb9",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":180,
                        "height":60}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"312587e83c344d069b8d040effb43676",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"eb41e6fa90554a9ba2a98f3cf8459eb9",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":180,
                            "height":60}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/главная/u137.png"}}]}]}]}}},
  "objectPaths":{
    "31c307833e7645eb8f52c20b04dacc1b":{
      "scriptId":"u0",
      "a8159063e477466e9fbce07355c5e82a":{
        "scriptId":"u1"},
      "14084ae3f8f8479588a4eb0d87987a24":{
        "scriptId":"u2"},
      "402b7d65930e42c8ab2b58703829c3ff":{
        "scriptId":"u3"},
      "8ad1a3f0f46946ed954c921a048a927a":{
        "scriptId":"u4"},
      "045f645385594381bc81c84af8d10830":{
        "scriptId":"u5"},
      "4f46ba15deff4634beb81ce43f2ac724":{
        "scriptId":"u6"},
      "8fbf82e26ca642d49cb090ebc8bcf612":{
        "scriptId":"u7"},
      "6d3c901a6f17447093f7170463b3d62f":{
        "scriptId":"u8"},
      "0421c61f4a634d8bb20bd46d208e517c":{
        "scriptId":"u9"},
      "887fd71470d44bfaa854cdb2fa05b565":{
        "scriptId":"u10"},
      "f3ab24dd2c0e4dc2bf2496df9596c924":{
        "scriptId":"u11"},
      "427256a81d85467994b76439cebc69ca":{
        "scriptId":"u12"},
      "6931673c584c49f6975614fa7e02d39d":{
        "scriptId":"u13"},
      "1d6d6f7c2ec84f3893bf64c4d3fcb99c":{
        "scriptId":"u14"},
      "85395471d60a476b83ec4368b18b85ea":{
        "scriptId":"u15"},
      "286ebe8d7e7a4fe48a4253e08f63871e":{
        "scriptId":"u16"},
      "a5014b69e8784418a9f156e60602cebf":{
        "scriptId":"u17"},
      "3e53a03a52bb4e1dab7eadf87174205f":{
        "scriptId":"u18"},
      "677f9235f89546e6b497a67782fd35cd":{
        "scriptId":"u19"},
      "5c250de23dc04c7992b97239bee7693e":{
        "scriptId":"u20"},
      "85e31ddecc0540968f0183d5ce0e04a0":{
        "scriptId":"u21"},
      "f81a839fa3ec462f9d07447cb7d5ea94":{
        "scriptId":"u22"},
      "09022a734e2d4cf9affff1988afcb311":{
        "scriptId":"u23"},
      "a2f3a6dc6b8a4ffd93187d27b302bb68":{
        "scriptId":"u24"},
      "fc37cbff9aec48eaa002a4a4c3715274":{
        "scriptId":"u25"},
      "160169868a5041da9050a8dc8f4f02d1":{
        "scriptId":"u26"},
      "61d1fb7bf72d454c88b0d1c29ed72de4":{
        "scriptId":"u27"},
      "effa31e5f1764b8d8abdeef0bc7e3e61":{
        "scriptId":"u28"},
      "1a3841491b4e4deab50f395a461f622f":{
        "scriptId":"u29"},
      "6184d0914218429d831029072917da31":{
        "scriptId":"u30"},
      "a570c4bf1e0a4ddcb13ae8cf8add5552":{
        "scriptId":"u31"}},
    "de515e0a24434c65b9ba9416d2dbc98d":{
      "scriptId":"u32"},
    "0a16281b9dbc4f9a9bf47abb247e4c3f":{
      "scriptId":"u33"},
    "62a9ad59a1024d96bdc528eddf9f72a9":{
      "scriptId":"u34"},
    "2b005d1f7fe14ec08ef3e8507744fbf7":{
      "scriptId":"u35"},
    "0265dd46ab0f4acfa2805e5c0dbb257b":{
      "scriptId":"u36",
      "71b1b9b974134a54a48c7eea3e9a7b5e":{
        "scriptId":"u37"},
      "c98c4e1f42b349878fed7662313b23fc":{
        "scriptId":"u38"},
      "67f741985f78439b8bbdee033141be15":{
        "scriptId":"u39"},
      "14e95f72b7694b508ce5ae0298078d9a":{
        "scriptId":"u40"},
      "2a1a47c0df9e4de38762ba3c9d06e9ec":{
        "scriptId":"u41"},
      "20f09b4d617041aabfe01cd4d58309c4":{
        "scriptId":"u42"},
      "2d0d2c4ff18d4780b7945a341bb96cde":{
        "scriptId":"u43"},
      "ef5f1707be2344a69d13c8738a3bebc2":{
        "scriptId":"u44"},
      "855ae197207143bd96db215b131e460f":{
        "scriptId":"u45"},
      "8544e519cdb940c78c851080d7abbb93":{
        "scriptId":"u46"},
      "714650cc2758420dac5fd70b7b9a1a3c":{
        "scriptId":"u47"},
      "4e0febc63ac3463db7bfac48ac5afe94":{
        "scriptId":"u48"},
      "88fcdb9596d944a8b9ae9b402e0e7ebb":{
        "scriptId":"u49"}},
    "a8594456e9c5468f8912de1ac2f1b1aa":{
      "scriptId":"u50"},
    "46000bfdebbf400d8fc5482185655293":{
      "scriptId":"u51"},
    "3630c3c74bbd46279cc727551a627527":{
      "scriptId":"u52"},
    "7d7eaadd348f4dd9b3370927e7e0ac8b":{
      "scriptId":"u53"},
    "f48bf3d825944702883ec0cc0dd6d7ba":{
      "scriptId":"u54"},
    "cec374e24c974981a7c1b987a1c64e12":{
      "scriptId":"u55"},
    "26d3acec33414e898e23e61b1d44ad03":{
      "scriptId":"u56"},
    "ae136b4aae4a422dadb371321208283d":{
      "scriptId":"u57"},
    "059a5c05b5ab410497f81f6c98a3c1a0":{
      "scriptId":"u58"},
    "03929fe99d744c8598f9948b5de8cdc7":{
      "scriptId":"u59"},
    "e4df8831edc44b8690cee6a89c2befcd":{
      "scriptId":"u60"},
    "72c0cdba90a34e73accd7971551c33e9":{
      "scriptId":"u61"},
    "c2f70723a56a411f8047ebe5bab5ca82":{
      "scriptId":"u62"},
    "1eeb1e33a345418082677899ff20a7fe":{
      "scriptId":"u63"},
    "8757d2f4676549d196e480578740b0e7":{
      "scriptId":"u64"},
    "5d6d48d8fc4c42f2ae4e3a0d87b0fde2":{
      "scriptId":"u65"},
    "2de481f096744e6a867207c66ec0215c":{
      "scriptId":"u66"},
    "e5e21a46cddf4c698a753c2ab3117411":{
      "scriptId":"u67"},
    "d94054663f894c4d8bd34ea5af1e2124":{
      "scriptId":"u68"},
    "6f2309a8f97d46f6bafe793fbe295b0f":{
      "scriptId":"u69"},
    "cafeb2897b84492bb41755af3bf38e63":{
      "scriptId":"u70"},
    "2c883982030e49c99daa69ee9203e090":{
      "scriptId":"u71"},
    "79c0626e572d47d9b58b99b4930878e4":{
      "scriptId":"u72"},
    "16c6a193af4c4565b8fc3e9e97eba638":{
      "scriptId":"u73"},
    "ed3f6508e3d84f90a5096e33509ddfb3":{
      "scriptId":"u74"},
    "15eb0227eb534e87a432ca9bd5f16c40":{
      "scriptId":"u75"},
    "368ca48ed8a748f0b13902beca2141cc":{
      "scriptId":"u76"},
    "2e50385383fb49c1bd39f6d5ab97a1c1":{
      "scriptId":"u77"},
    "def7bb152f6f4d32ba61367501f60ca1":{
      "scriptId":"u78"},
    "1d8a155bc29641f88bff23ccb5c396f4":{
      "scriptId":"u79"},
    "f95eaa291442499eb2ffc6e810a7f96d":{
      "scriptId":"u80"},
    "6b4424e1d3b445e394f41c1df50dfa84":{
      "scriptId":"u81",
      "e08c2a7d5878465d8431a3e82ac01d11":{
        "scriptId":"u82"},
      "6bf81276138145e4a69d32f79ad6e41a":{
        "scriptId":"u83"},
      "5d65676a59cb4c27b2affd3dd530a65c":{
        "scriptId":"u84"},
      "57140586a7ee4b43aa3a6692a99c8594":{
        "scriptId":"u85"},
      "f662fbd30ce8436cb40cb7ae8cc14011":{
        "scriptId":"u86"},
      "bd8018d9401b41d7b27ca97c96fded4c":{
        "scriptId":"u87"},
      "0f3e0bd7dd12496eb31b35833006f39c":{
        "scriptId":"u88"},
      "cc1f87e161d84506816c03e29c7b764c":{
        "scriptId":"u89"},
      "9b18b1aed72a4283aa89bc3289c656d5":{
        "scriptId":"u90"},
      "3fbb36f21ade491ab9eb2882d63cf415":{
        "scriptId":"u91"},
      "f8dc6c145c2f41f4aa942b82cdc964f9":{
        "scriptId":"u92"},
      "f207725a28ac4c3f9be5a2ba54a67d41":{
        "scriptId":"u93"},
      "e25359213d124160aa87ca25b79b9286":{
        "scriptId":"u94"},
      "c9cd99cd79924d75826942ea76870e31":{
        "scriptId":"u95"},
      "26709191915e427bb77a5de4707d0a5c":{
        "scriptId":"u96"},
      "47334483f651417bb65616b5431c73f7":{
        "scriptId":"u97"},
      "c1d9d316058442a1bf306cb63481d033":{
        "scriptId":"u98"},
      "b69a917f5ecd4416a193b64512c4cee4":{
        "scriptId":"u99"},
      "74127ee343cd4002ba47363614659620":{
        "scriptId":"u100"},
      "482e38d110eb4855afc10e82db94eaae":{
        "scriptId":"u101"},
      "672c1a628ac5438db7e3e34dd57798af":{
        "scriptId":"u102"},
      "4075f77a503941b998eb5a49a505f1ef":{
        "scriptId":"u103"},
      "b8b7eb3c9cf24ddca53af376039eda8c":{
        "scriptId":"u104"},
      "c1e0c1209227463d99b493e36858dbcd":{
        "scriptId":"u105"},
      "f3dfa111fd5c4c1fb51c2e512c6aaa14":{
        "scriptId":"u106"},
      "97d1433241e64671918bf24e66165869":{
        "scriptId":"u107"},
      "da40d25c119b42dda5bb2ea76ad449a6":{
        "scriptId":"u108"},
      "2927063ec1074054b80daabb05653b43":{
        "scriptId":"u109"},
      "e327dd1eef584794bcae0e0226f4263c":{
        "scriptId":"u110"},
      "a4a0459e97374e1ea41e6b02e0cf2871":{
        "scriptId":"u111"},
      "b8dacec1e6b94fc8b0692c021db18514":{
        "scriptId":"u112"},
      "c76cfd1b69574f54b1bab98c9fdbe226":{
        "scriptId":"u113"},
      "eb41e6fa90554a9ba2a98f3cf8459eb9":{
        "scriptId":"u114"},
      "0f3335600b4d4e0f868bc4627d53f23b":{
        "scriptId":"u115"},
      "312587e83c344d069b8d040effb43676":{
        "scriptId":"u116"}}}});