//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logic.Properties.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принят.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос на добавление my-crypt.
        /// </summary>
        public static string AddMyCryptTransaction {
            get {
                return ResourceManager.GetString("AddMyCryptTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор мысли.
        /// </summary>
        public static string AuthorWords {
            get {
                return ResourceManager.GetString("AuthorWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидает подтверждения.
        /// </summary>
        public static string AwaitingConfirm {
            get {
                return ResourceManager.GetString("AwaitingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банк.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование банка.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платежная система: Банк.
        /// </summary>
        public static string BankPaymentSystem {
            get {
                return ResourceManager.GetString("BankPaymentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платежные системы: Банк.
        /// </summary>
        public static string BankPaymentSystems {
            get {
                return ResourceManager.GetString("BankPaymentSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банки.
        /// </summary>
        public static string Banks {
            get {
                return ResourceManager.GetString("Banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка на участие в торгах.
        /// </summary>
        public static string BiddingParticipateApplication {
            get {
                return ResourceManager.GetString("BiddingParticipateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки на участие в торгах.
        /// </summary>
        public static string BiddingParticipateApplications {
            get {
                return ResourceManager.GetString("BiddingParticipateApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БИК.
        /// </summary>
        public static string BIK {
            get {
                return ResourceManager.GetString("BIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внесено достаточное количество денег.
        /// </summary>
        public static string BillPaymentStat__EnoughMoney {
            get {
                return ResourceManager.GetString("BillPaymentStat__EnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счет не оплачен.
        /// </summary>
        public static string BillPaymentStat__NotPaid {
            get {
                return ResourceManager.GetString("BillPaymentStat__NotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счет оплачен.
        /// </summary>
        public static string BillPaymentStat__Paid {
            get {
                return ResourceManager.GetString("BillPaymentStat__Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидает оплаты.
        /// </summary>
        public static string BillPaymentStat__WaitingPayment {
            get {
                return ResourceManager.GetString("BillPaymentStat__WaitingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние счета.
        /// </summary>
        public static string BillPaymentState {
            get {
                return ResourceManager.GetString("BillPaymentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупатель.
        /// </summary>
        public static string Buyer {
            get {
                return ResourceManager.GetString("Buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер карты.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент проверочного платежа.
        /// </summary>
        public static string CheckPaymentPercent {
            get {
                return ResourceManager.GetString("CheckPaymentPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корреспондентский счет.
        /// </summary>
        public static string CorrespondentAccount {
            get {
                return ResourceManager.GetString("CorrespondentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string CreationDateTime {
            get {
                return ResourceManager.GetString("CreationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий счет.
        /// </summary>
        public static string CurrentAccount {
            get {
                return ResourceManager.GetString("CurrentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дефолтная платежная система.
        /// </summary>
        public static string DefaultPaymentSystem {
            get {
                return ResourceManager.GetString("DefaultPaymentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отклонен.
        /// </summary>
        public static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная.
        /// </summary>
        public static string Electronic {
            get {
                return ResourceManager.GetString("Electronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навание электронной системы.
        /// </summary>
        public static string ElectronicName {
            get {
                return ResourceManager.GetString("ElectronicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платежная система: Электронная платёжная система.
        /// </summary>
        public static string ElectronicPaymentSystem {
            get {
                return ResourceManager.GetString("ElectronicPaymentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задано.
        /// </summary>
        public static string EmptyPropertie {
            get {
                return ResourceManager.GetString("EmptyPropertie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аргумент {0} не задан.
        /// </summary>
        public static string Exception_ArgumentNull {
            get {
                return ResourceManager.GetString("Exception_ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойство {0} не задано. Невозможно продолжить операцию.
        /// </summary>
        public static string Exception_PropertieNotSet {
            get {
                return ResourceManager.GetString("Exception_PropertieNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИНН.
        /// </summary>
        public static string INN {
            get {
                return ResourceManager.GetString("INN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КПП.
        /// </summary>
        public static string KPP {
            get {
                return ResourceManager.GetString("KPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное колличество mycrypto.
        /// </summary>
        public static string MaxMyCryptCount {
            get {
                return ResourceManager.GetString("MaxMyCryptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деньги.
        /// </summary>
        public static string MoneyAmount {
            get {
                return ResourceManager.GetString("MoneyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество my-crypt.
        /// </summary>
        public static string MyCryptCount {
            get {
                return ResourceManager.GetString("MyCryptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определен.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платеж.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платежи.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платежная система.
        /// </summary>
        public static string PaymentSystem {
            get {
                return ResourceManager.GetString("PaymentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа платежных систем.
        /// </summary>
        public static string PaymentSystemGroup {
            get {
                return ResourceManager.GetString("PaymentSystemGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы платежных систем.
        /// </summary>
        public static string PaymentSystemGroups {
            get {
                return ResourceManager.GetString("PaymentSystemGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платежные системы.
        /// </summary>
        public static string PaymentSystems {
            get {
                return ResourceManager.GetString("PaymentSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент доходности.
        /// </summary>
        public static string ProfitPercent {
            get {
                return ResourceManager.GetString("ProfitPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер кошелька.
        /// </summary>
        public static string PurseNumber {
            get {
                return ResourceManager.GetString("PurseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Котировка.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Случайные мысли.
        /// </summary>
        public static string RandomWords {
            get {
                return ResourceManager.GetString("RandomWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список прибылей от рефералов.
        /// </summary>
        public static string RefererProfits {
            get {
                return ResourceManager.GetString("RefererProfits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продавец.
        /// </summary>
        public static string Saller {
            get {
                return ResourceManager.GetString("Saller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки системы.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} %.
        /// </summary>
        public static string Systemsettings__ProfitPercent_DisplayString {
            get {
                return ResourceManager.GetString("Systemsettings__ProfitPercent_DisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 к {0}.
        /// </summary>
        public static string Systemsettings__Quote_DisplayString {
            get {
                return ResourceManager.GetString("Systemsettings__Quote_DisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст мысли.
        /// </summary>
        public static string TextWords {
            get {
                return ResourceManager.GetString("TextWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Торговая сессия.
        /// </summary>
        public static string TradingSession {
            get {
                return ResourceManager.GetString("TradingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжительность торговой сессии.
        /// </summary>
        public static string TradingSessionDuration {
            get {
                return ResourceManager.GetString("TradingSessionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние торговой сессии.
        /// </summary>
        public static string TradingSessionState {
            get {
                return ResourceManager.GetString("TradingSessionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забанена.
        /// </summary>
        public static string TradingSessionStatus__Baned {
            get {
                return ResourceManager.GetString("TradingSessionStatus__Baned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыта.
        /// </summary>
        public static string TradingSessionStatus__Closed {
            get {
                return ResourceManager.GetString("TradingSessionStatus__Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не открыта.
        /// </summary>
        public static string TradingSessionStatus__NA {
            get {
                return ResourceManager.GetString("TradingSessionStatus__NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо обеспечить доходность.
        /// </summary>
        public static string TradingSessionStatus__NeedEnsureProfibility {
            get {
                return ResourceManager.GetString("TradingSessionStatus__NeedEnsureProfibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание прибыли для покупателя.
        /// </summary>
        public static string TradingSessionStatus__NeedProfit {
            get {
                return ResourceManager.GetString("TradingSessionStatus__NeedProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыта.
        /// </summary>
        public static string TradingSessionStatus__Open {
            get {
                return ResourceManager.GetString("TradingSessionStatus__Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвержление прибыли покупателем.
        /// </summary>
        public static string TradingSessionStatus__ProfitConfirmation {
            get {
                return ResourceManager.GetString("TradingSessionStatus__ProfitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В режиме ожидания.
        /// </summary>
        public static string TradingSessionStatus__SessionInProgress {
            get {
                return ResourceManager.GetString("TradingSessionStatus__SessionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание старта.
        /// </summary>
        public static string TradingSessionStatus__WaitForProgressStart {
            get {
                return ResourceManager.GetString("TradingSessionStatus__WaitForProgressStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер транзакции.
        /// </summary>
        public static string TransactionNumber {
            get {
                return ResourceManager.GetString("TransactionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество пользователя.
        /// </summary>
        public static string UserPatronymic {
            get {
                return ResourceManager.GetString("UserPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия пользователя.
        /// </summary>
        public static string UserSurname {
            get {
                return ResourceManager.GetString("UserSurname", resourceCulture);
            }
        }
    }
}
