$axure.loadCurrentPage({
  "url":"апм___комментарии_в_новостном_отделе.html",
  "generationDate":new Date(1390755600745.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"IsRegistred"],
  "page":{
    "packageId":"03cb2f8f1b844fe7b869ce2346b041ee",
    "type":"Axure:Page",
    "name":"АПМ | Комментарии в новостном отделе",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"df070cff28e743e79e965a97057167c8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":974}},
          "adaptiveStyles":{
},
          "masterId":"18f5f2c19e63498db99061699d0d00d5"},
{
          "id":"3808e69e3360484aa304ebdb2affd94e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"8e3681daf2334685b97d5cce483127b0"},
{
          "id":"a584b60fe0564477a96535dd3c72b411",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":120},
            "size":{
              "width":740,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"134c08dba5b14872abc39bb86f05f2f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":120},
                "size":{
                  "width":740,
                  "height":410}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/апм___комментарии_в_новостном_отделе/u43.png"}},
{
          "id":"75bb0c2b4e5f4656987be9db2720c93e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":150},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/апу___отправить_письмо/u84_line.png"}},
{
          "id":"0b482a460f164096b69c6738c99a7662",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":477,
              "y":124},
            "size":{
              "width":291,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5d81e1235054e7ba9c1d607da129b08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":477,
                  "y":124},
                "size":{
                  "width":291,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f60e7905b6a417d8106e20daacc58cc",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"b5d7cf91a6eb42ecbf1400ed7d82449c"},
{
          "id":"f86bda4f6fc747a4a1dd3d6d4fb18abe",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":175},
            "size":{
              "width":310,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"099f51424dcf4cbbbfa6d4864f0977ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":182},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04071a70cb7843a79e7d010019bfaaea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":182},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3806ed365e48424984331cb1f264ca0f",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":230},
            "size":{
              "width":700,
              "height":220}},
          "adaptiveStyles":{
}},
{
          "id":"db7b2e1902314afe8758b02dbac169c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":246},
            "size":{
              "width":142,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dbc6ff5dc5a4cda8e0069bf64379427",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":246},
                "size":{
                  "width":142,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8912c216494940b7b1446a971b25dfa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":286},
            "size":{
              "width":660,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2376b9ea5a1b4e1da1188c0ba80dcca1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":286},
                "size":{
                  "width":660,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ced65bd41e1f45e68e464412be00424e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":480},
            "size":{
              "width":150,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "18f5f2c19e63498db99061699d0d00d5":{
      "packageId":"18f5f2c19e63498db99061699d0d00d5",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a8159063e477466e9fbce07355c5e82a",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":30,
                "y":994},
              "size":{
                "width":100,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"14084ae3f8f8479588a4eb0d87987a24",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":30,
                    "y":994},
                  "size":{
                    "width":100,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u1.png"}},
{
            "id":"402b7d65930e42c8ab2b58703829c3ff",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":974},
              "size":{
                "width":920,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF999999}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/главная/u3_line.png"}},
{
            "id":"8ad1a3f0f46946ed954c921a048a927a",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":232,
                "y":994},
              "size":{
                "width":100,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"045f645385594381bc81c84af8d10830",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":232,
                    "y":994},
                  "size":{
                    "width":100,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u1.png"}},
{
            "id":"4f46ba15deff4634beb81ce43f2ac724",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":440,
                "y":994},
              "size":{
                "width":100,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8fbf82e26ca642d49cb090ebc8bcf612",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":440,
                    "y":994},
                  "size":{
                    "width":100,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u1.png"}},
{
            "id":"6d3c901a6f17447093f7170463b3d62f",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":670,
                "y":994},
              "size":{
                "width":100,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0421c61f4a634d8bb20bd46d208e517c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":670,
                    "y":994},
                  "size":{
                    "width":100,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u1.png"}},
{
            "id":"887fd71470d44bfaa854cdb2fa05b565",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":900,
                "y":994},
              "size":{
                "width":100,
                "height":90},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f3ab24dd2c0e4dc2bf2496df9596c924",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":900,
                    "y":994},
                  "size":{
                    "width":100,
                    "height":90},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u1.png"}},
{
            "id":"427256a81d85467994b76439cebc69ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":44,
                "y":1094},
              "size":{
                "width":72,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6931673c584c49f6975614fa7e02d39d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":44,
                    "y":1094},
                  "size":{
                    "width":72,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1d6d6f7c2ec84f3893bf64c4d3fcb99c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":254,
                "y":1094},
              "size":{
                "width":56,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"85395471d60a476b83ec4368b18b85ea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":254,
                    "y":1094},
                  "size":{
                    "width":56,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"286ebe8d7e7a4fe48a4253e08f63871e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":444,
                "y":1094},
              "size":{
                "width":93,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a5014b69e8784418a9f156e60602cebf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":444,
                    "y":1094},
                  "size":{
                    "width":93,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3e53a03a52bb4e1dab7eadf87174205f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":706,
                "y":1094},
              "size":{
                "width":27,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"677f9235f89546e6b497a67782fd35cd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":706,
                    "y":1094},
                  "size":{
                    "width":27,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5c250de23dc04c7992b97239bee7693e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "location":{
                "x":894,
                "y":1094},
              "size":{
                "width":111,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"85e31ddecc0540968f0183d5ce0e04a0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "location":{
                    "x":894,
                    "y":1094},
                  "size":{
                    "width":111,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f81a839fa3ec462f9d07447cb7d5ea94",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":55,
                "y":1013},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"09022a734e2d4cf9affff1988afcb311",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":55,
                    "y":1013},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u22.png"}},
{
            "id":"a2f3a6dc6b8a4ffd93187d27b302bb68",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":257,
                "y":1014},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fc37cbff9aec48eaa002a4a4c3715274",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":257,
                    "y":1014},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u22.png"}},
{
            "id":"160169868a5041da9050a8dc8f4f02d1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":465,
                "y":1014},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"61d1fb7bf72d454c88b0d1c29ed72de4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":465,
                    "y":1014},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u22.png"}},
{
            "id":"effa31e5f1764b8d8abdeef0bc7e3e61",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":695,
                "y":1014},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1a3841491b4e4deab50f395a461f622f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":695,
                    "y":1014},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u22.png"}},
{
            "id":"6184d0914218429d831029072917da31",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":925,
                "y":1014},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a570c4bf1e0a4ddcb13ae8cf8add5552",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":925,
                    "y":1014},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u22.png"}}]}},
    "8e3681daf2334685b97d5cce483127b0":{
      "packageId":"8e3681daf2334685b97d5cce483127b0",
      "type":"Axure:Master",
      "name":"Навигация по админке модератора",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b8c3134b7f5a42659c2f6fb33d235010",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":120},
              "size":{
                "width":180,
                "height":280}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5b7c45801d7a450abe1d54653b2cf330",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":120},
                  "size":{
                    "width":180,
                    "height":280}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/админ_панель_модератора/u69.png"}},
{
            "id":"9fa647c1919346a8b8788a22b19d7e4b",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":210},
              "size":{
                "width":180,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/админ_панель_участника/u35_line.png"}},
{
            "id":"a6895e25e19b4967bcb1d0feb7b91505",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":300},
              "size":{
                "width":180,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/админ_панель_участника/u35_line.png"}},
{
            "id":"d0e7ea8a6bc04248b3708f429cbb24f8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "horizontalAlignment":"center",
              "location":{
                "x":30,
                "y":136},
              "size":{
                "width":161,
                "height":66}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d3c4cae7f8474373a74a79d69a43faa3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "horizontalAlignment":"center",
                  "location":{
                    "x":30,
                    "y":136},
                  "size":{
                    "width":161,
                    "height":66}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Админ панель модератора in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"админ_панель_модератора.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b5797ee130c742d9ac3a32dd03c6db59",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "horizontalAlignment":"center",
              "location":{
                "x":36,
                "y":246},
              "size":{
                "width":153,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ca82e3106d7a4b6c8a94db6ed0101f17",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "horizontalAlignment":"center",
                  "location":{
                    "x":36,
                    "y":246},
                  "size":{
                    "width":153,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open АПМ | Комментарии в новостном отделе in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"апм___комментарии_в_новостном_отделе.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"88bde1a92a344b7a9bc467ea0ef8c437",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "horizontalAlignment":"center",
              "location":{
                "x":40,
                "y":336},
              "size":{
                "width":139,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c1cf4607c0ba41f8bfa46734bf201b30",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "horizontalAlignment":"center",
                  "location":{
                    "x":40,
                    "y":336},
                  "size":{
                    "width":139,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open АПМ | Редактирование пользователей in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"апм___редактирование_пользователей.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "b5d7cf91a6eb42ecbf1400ed7d82449c":{
      "packageId":"b5d7cf91a6eb42ecbf1400ed7d82449c",
      "type":"Axure:Master",
      "name":"Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e08c2a7d5878465d8431a3e82ac01d11",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":460,
                "y":10},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6bf81276138145e4a69d32f79ad6e41a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":460,
                    "y":10},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u122.png"}},
{
            "id":"5d65676a59cb4c27b2affd3dd530a65c",
            "label":"Вход | Регистрация",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":700,
                "y":10},
              "size":{
                "width":310,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onLoad":{
                "description":"OnLoad",
                "cases":[{
                    "description":"Case 1<br> (If value of IsRegistred equals &quot;true&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"IsRegistred"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"true",
                        "stos":[]}},
                    "actions":[{
                        "action":"setPanelState",
                        "description":"Set Вход | Регистрация to Информация о пользователе",
                        "panelsToStates":[{
                            "panelPath":["5d65676a59cb4c27b2affd3dd530a65c"],
                            "stateInfo":{
                              "setStateType":"diagram",
                              "stateNumber":2,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":false,
                              "showWhenSet":false,
                              "options":{
                                "compress":false}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"1e672d456b8741f39fa27106b1beb640",
                "label":"Вход | Регистрация",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"57140586a7ee4b43aa3a6692a99c8594",
                    "label":"",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":310,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f662fbd30ce8436cb40cb7ae8cc14011",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":310,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/главная/u125.png"}},
{
                    "id":"bd8018d9401b41d7b27ca97c96fded4c",
                    "label":"",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"verticalLine",
                    "styleType":"verticalLine",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":95,
                        "y":0},
                      "size":{
                        "width":10,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "images":{
                      "start~":"resources/images/transparent.gif",
                      "end~":"resources/images/transparent.gif",
                      "line~":"images/главная/u127_line.png"}},
{
                    "id":"0f3e0bd7dd12496eb31b35833006f39c",
                    "label":"",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"28px",
                      "location":{
                        "x":15,
                        "y":8},
                      "size":{
                        "width":63,
                        "height":33}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"cc1f87e161d84506816c03e29c7b764c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"28px",
                          "location":{
                            "x":15,
                            "y":8},
                          "size":{
                            "width":63,
                            "height":33}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"fadeWidget",
                                "description":"Toggle Форма входа",
                                "objectsToFades":[{
                                    "objectPath":["e25359213d124160aa87ca25b79b9286"],
                                    "fadeInfo":{
                                      "fadeType":"toggle",
                                      "options":{
                                        "showType":"none"}}}]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"9b18b1aed72a4283aa89bc3289c656d5",
                    "label":"",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":125,
                        "y":7},
                      "size":{
                        "width":10,
                        "height":10}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Регистрация in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"регистрация.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "scrollbars":"none",
                    "fitToContent":true,
                    "propagate":false,
                    "diagrams":[{
                        "id":"73fbc92942b5422d88338fa50da0191c",
                        "label":"State1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"3fbb36f21ade491ab9eb2882d63cf415",
                            "label":"Перейти в регистрацию",
                            "parentDynamicPanel":"9b18b1aed72a4283aa89bc3289c656d5",
                            "type":"dynamicPanel",
                            "styleType":"dynamicPanel",
                            "visible":true,
                            "style":{
                              "size":{
                                "width":10,
                                "height":10}},
                            "adaptiveStyles":{
},
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"Open Регистрация in Current Window",
                                        "target":{
                                          "targetType":"page",
                                          "url":"регистрация.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "scrollbars":"none",
                            "fitToContent":true,
                            "propagate":false,
                            "diagrams":[{
                                "id":"ad4c92a6f0e147b2b4d82106bd45adfb",
                                "label":"State1",
                                "type":"Axure:PanelDiagram",
                                "objects":[{
                                    "id":"f8dc6c145c2f41f4aa942b82cdc964f9",
                                    "label":"",
                                    "parentDynamicPanel":"3fbb36f21ade491ab9eb2882d63cf415",
                                    "type":"buttonShape",
                                    "styleType":"paragraph",
                                    "visible":true,
                                    "style":{
                                      "fontSize":"28px",
                                      "size":{
                                        "width":170,
                                        "height":40}},
                                    "adaptiveStyles":{
},
                                    "objects":[{
                                        "id":"f207725a28ac4c3f9be5a2ba54a67d41",
                                        "label":"",
                                        "isContained":true,
                                        "parentDynamicPanel":"3fbb36f21ade491ab9eb2882d63cf415",
                                        "type":"richTextPanel",
                                        "styleType":"paragraph",
                                        "visible":true,
                                        "style":{
                                          "fontSize":"28px",
                                          "size":{
                                            "width":170,
                                            "height":40}},
                                        "adaptiveStyles":{
}}],
                                    "images":{
                                      "normal~":"resources/images/transparent.gif"}}]}]}]}]},
{
                    "id":"e25359213d124160aa87ca25b79b9286",
                    "label":"Форма входа",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":false,
                    "style":{
                      "location":{
                        "x":0,
                        "y":70},
                      "size":{
                        "width":10,
                        "height":10},
                      "visible":false},
                    "adaptiveStyles":{
},
                    "scrollbars":"none",
                    "fitToContent":true,
                    "propagate":false,
                    "diagrams":[{
                        "id":"6f7b56455f3c40d4bf33b8fabc998f48",
                        "label":"State1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"c9cd99cd79924d75826942ea76870e31",
                            "label":"",
                            "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                            "type":"buttonShape",
                            "styleType":"buttonShape",
                            "visible":true,
                            "style":{
                              "size":{
                                "width":310,
                                "height":150}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"26709191915e427bb77a5de4707d0a5c",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "size":{
                                    "width":310,
                                    "height":150}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"images/главная/u135.png"}},
{
                            "id":"47334483f651417bb65616b5431c73f7",
                            "label":"",
                            "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                            "type":"textBox",
                            "styleType":"textBox",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":15,
                                "y":20},
                              "size":{
                                "width":275,
                                "height":25}},
                            "adaptiveStyles":{
}},
{
                            "id":"c1d9d316058442a1bf306cb63481d033",
                            "label":"",
                            "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                            "type":"textBox",
                            "styleType":"textBox",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":15,
                                "y":70},
                              "size":{
                                "width":275,
                                "height":25}},
                            "adaptiveStyles":{
}},
{
                            "id":"b69a917f5ecd4416a193b64512c4cee4",
                            "label":"",
                            "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":24,
                                "y":23},
                              "size":{
                                "width":36,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"74127ee343cd4002ba47363614659620",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "location":{
                                    "x":24,
                                    "y":23},
                                  "size":{
                                    "width":36,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"482e38d110eb4855afc10e82db94eaae",
                            "label":"",
                            "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":24,
                                "y":74},
                              "size":{
                                "width":45,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"672c1a628ac5438db7e3e34dd57798af",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "location":{
                                    "x":24,
                                    "y":74},
                                  "size":{
                                    "width":45,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"4075f77a503941b998eb5a49a505f1ef",
                            "label":"",
                            "parentDynamicPanel":"e25359213d124160aa87ca25b79b9286",
                            "type":"button",
                            "styleType":"button",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":190,
                                "y":115},
                              "size":{
                                "width":100,
                                "height":25}},
                            "adaptiveStyles":{
},
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"Open Админ панель участника in Current Window",
                                        "target":{
                                          "targetType":"page",
                                          "url":"админ_панель_участника.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true}]}]}]},
{
                "id":"7751348731ea43fda9d7a4cf751ff4e0",
                "label":"Информация о пользователе",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b8b7eb3c9cf24ddca53af376039eda8c",
                    "label":"",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":310,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c1e0c1209227463d99b493e36858dbcd",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":310,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/главная/u125.png"}},
{
                    "id":"f3dfa111fd5c4c1fb51c2e512c6aaa14",
                    "label":"",
                    "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "location":{
                        "x":41,
                        "y":13},
                      "size":{
                        "width":228,
                        "height":24}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"97d1433241e64671918bf24e66165869",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5d65676a59cb4c27b2affd3dd530a65c",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "location":{
                            "x":41,
                            "y":13},
                          "size":{
                            "width":228,
                            "height":24}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]},
{
            "id":"da40d25c119b42dda5bb2ea76ad449a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "location":{
                "x":522,
                "y":18},
              "size":{
                "width":57,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2927063ec1074054b80daabb05653b43",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "location":{
                    "x":522,
                    "y":18},
                  "size":{
                    "width":57,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e327dd1eef584794bcae0e0226f4263c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":232,
                "y":10},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a4a0459e97374e1ea41e6b02e0cf2871",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":232,
                    "y":10},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/главная/u122.png"}},
{
            "id":"b8dacec1e6b94fc8b0692c021db18514",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "location":{
                "x":278,
                "y":18},
              "size":{
                "width":75,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c76cfd1b69574f54b1bab98c9fdbe226",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "location":{
                    "x":278,
                    "y":18},
                  "size":{
                    "width":75,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"eb41e6fa90554a9ba2a98f3cf8459eb9",
            "label":"Перейти на главную",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":10},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Главная in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"главная.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"db15717b5e48406fbe54dbd6dc532258",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"0f3335600b4d4e0f868bc4627d53f23b",
                    "label":"",
                    "parentDynamicPanel":"eb41e6fa90554a9ba2a98f3cf8459eb9",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":180,
                        "height":60}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"312587e83c344d069b8d040effb43676",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"eb41e6fa90554a9ba2a98f3cf8459eb9",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":180,
                            "height":60}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/главная/u155.png"}}]}]}]}}},
  "objectPaths":{
    "df070cff28e743e79e965a97057167c8":{
      "scriptId":"u0",
      "a8159063e477466e9fbce07355c5e82a":{
        "scriptId":"u1"},
      "14084ae3f8f8479588a4eb0d87987a24":{
        "scriptId":"u2"},
      "402b7d65930e42c8ab2b58703829c3ff":{
        "scriptId":"u3"},
      "8ad1a3f0f46946ed954c921a048a927a":{
        "scriptId":"u4"},
      "045f645385594381bc81c84af8d10830":{
        "scriptId":"u5"},
      "4f46ba15deff4634beb81ce43f2ac724":{
        "scriptId":"u6"},
      "8fbf82e26ca642d49cb090ebc8bcf612":{
        "scriptId":"u7"},
      "6d3c901a6f17447093f7170463b3d62f":{
        "scriptId":"u8"},
      "0421c61f4a634d8bb20bd46d208e517c":{
        "scriptId":"u9"},
      "887fd71470d44bfaa854cdb2fa05b565":{
        "scriptId":"u10"},
      "f3ab24dd2c0e4dc2bf2496df9596c924":{
        "scriptId":"u11"},
      "427256a81d85467994b76439cebc69ca":{
        "scriptId":"u12"},
      "6931673c584c49f6975614fa7e02d39d":{
        "scriptId":"u13"},
      "1d6d6f7c2ec84f3893bf64c4d3fcb99c":{
        "scriptId":"u14"},
      "85395471d60a476b83ec4368b18b85ea":{
        "scriptId":"u15"},
      "286ebe8d7e7a4fe48a4253e08f63871e":{
        "scriptId":"u16"},
      "a5014b69e8784418a9f156e60602cebf":{
        "scriptId":"u17"},
      "3e53a03a52bb4e1dab7eadf87174205f":{
        "scriptId":"u18"},
      "677f9235f89546e6b497a67782fd35cd":{
        "scriptId":"u19"},
      "5c250de23dc04c7992b97239bee7693e":{
        "scriptId":"u20"},
      "85e31ddecc0540968f0183d5ce0e04a0":{
        "scriptId":"u21"},
      "f81a839fa3ec462f9d07447cb7d5ea94":{
        "scriptId":"u22"},
      "09022a734e2d4cf9affff1988afcb311":{
        "scriptId":"u23"},
      "a2f3a6dc6b8a4ffd93187d27b302bb68":{
        "scriptId":"u24"},
      "fc37cbff9aec48eaa002a4a4c3715274":{
        "scriptId":"u25"},
      "160169868a5041da9050a8dc8f4f02d1":{
        "scriptId":"u26"},
      "61d1fb7bf72d454c88b0d1c29ed72de4":{
        "scriptId":"u27"},
      "effa31e5f1764b8d8abdeef0bc7e3e61":{
        "scriptId":"u28"},
      "1a3841491b4e4deab50f395a461f622f":{
        "scriptId":"u29"},
      "6184d0914218429d831029072917da31":{
        "scriptId":"u30"},
      "a570c4bf1e0a4ddcb13ae8cf8add5552":{
        "scriptId":"u31"}},
    "3808e69e3360484aa304ebdb2affd94e":{
      "scriptId":"u32",
      "b8c3134b7f5a42659c2f6fb33d235010":{
        "scriptId":"u33"},
      "5b7c45801d7a450abe1d54653b2cf330":{
        "scriptId":"u34"},
      "9fa647c1919346a8b8788a22b19d7e4b":{
        "scriptId":"u35"},
      "a6895e25e19b4967bcb1d0feb7b91505":{
        "scriptId":"u36"},
      "d0e7ea8a6bc04248b3708f429cbb24f8":{
        "scriptId":"u37"},
      "d3c4cae7f8474373a74a79d69a43faa3":{
        "scriptId":"u38"},
      "b5797ee130c742d9ac3a32dd03c6db59":{
        "scriptId":"u39"},
      "ca82e3106d7a4b6c8a94db6ed0101f17":{
        "scriptId":"u40"},
      "88bde1a92a344b7a9bc467ea0ef8c437":{
        "scriptId":"u41"},
      "c1cf4607c0ba41f8bfa46734bf201b30":{
        "scriptId":"u42"}},
    "a584b60fe0564477a96535dd3c72b411":{
      "scriptId":"u43"},
    "134c08dba5b14872abc39bb86f05f2f8":{
      "scriptId":"u44"},
    "75bb0c2b4e5f4656987be9db2720c93e":{
      "scriptId":"u45"},
    "0b482a460f164096b69c6738c99a7662":{
      "scriptId":"u46"},
    "c5d81e1235054e7ba9c1d607da129b08":{
      "scriptId":"u47"},
    "1f60e7905b6a417d8106e20daacc58cc":{
      "scriptId":"u48",
      "e08c2a7d5878465d8431a3e82ac01d11":{
        "scriptId":"u49"},
      "6bf81276138145e4a69d32f79ad6e41a":{
        "scriptId":"u50"},
      "5d65676a59cb4c27b2affd3dd530a65c":{
        "scriptId":"u51"},
      "57140586a7ee4b43aa3a6692a99c8594":{
        "scriptId":"u52"},
      "f662fbd30ce8436cb40cb7ae8cc14011":{
        "scriptId":"u53"},
      "bd8018d9401b41d7b27ca97c96fded4c":{
        "scriptId":"u54"},
      "0f3e0bd7dd12496eb31b35833006f39c":{
        "scriptId":"u55"},
      "cc1f87e161d84506816c03e29c7b764c":{
        "scriptId":"u56"},
      "9b18b1aed72a4283aa89bc3289c656d5":{
        "scriptId":"u57"},
      "3fbb36f21ade491ab9eb2882d63cf415":{
        "scriptId":"u58"},
      "f8dc6c145c2f41f4aa942b82cdc964f9":{
        "scriptId":"u59"},
      "f207725a28ac4c3f9be5a2ba54a67d41":{
        "scriptId":"u60"},
      "e25359213d124160aa87ca25b79b9286":{
        "scriptId":"u61"},
      "c9cd99cd79924d75826942ea76870e31":{
        "scriptId":"u62"},
      "26709191915e427bb77a5de4707d0a5c":{
        "scriptId":"u63"},
      "47334483f651417bb65616b5431c73f7":{
        "scriptId":"u64"},
      "c1d9d316058442a1bf306cb63481d033":{
        "scriptId":"u65"},
      "b69a917f5ecd4416a193b64512c4cee4":{
        "scriptId":"u66"},
      "74127ee343cd4002ba47363614659620":{
        "scriptId":"u67"},
      "482e38d110eb4855afc10e82db94eaae":{
        "scriptId":"u68"},
      "672c1a628ac5438db7e3e34dd57798af":{
        "scriptId":"u69"},
      "4075f77a503941b998eb5a49a505f1ef":{
        "scriptId":"u70"},
      "b8b7eb3c9cf24ddca53af376039eda8c":{
        "scriptId":"u71"},
      "c1e0c1209227463d99b493e36858dbcd":{
        "scriptId":"u72"},
      "f3dfa111fd5c4c1fb51c2e512c6aaa14":{
        "scriptId":"u73"},
      "97d1433241e64671918bf24e66165869":{
        "scriptId":"u74"},
      "da40d25c119b42dda5bb2ea76ad449a6":{
        "scriptId":"u75"},
      "2927063ec1074054b80daabb05653b43":{
        "scriptId":"u76"},
      "e327dd1eef584794bcae0e0226f4263c":{
        "scriptId":"u77"},
      "a4a0459e97374e1ea41e6b02e0cf2871":{
        "scriptId":"u78"},
      "b8dacec1e6b94fc8b0692c021db18514":{
        "scriptId":"u79"},
      "c76cfd1b69574f54b1bab98c9fdbe226":{
        "scriptId":"u80"},
      "eb41e6fa90554a9ba2a98f3cf8459eb9":{
        "scriptId":"u81"},
      "0f3335600b4d4e0f868bc4627d53f23b":{
        "scriptId":"u82"},
      "312587e83c344d069b8d040effb43676":{
        "scriptId":"u83"}},
    "f86bda4f6fc747a4a1dd3d6d4fb18abe":{
      "scriptId":"u84"},
    "099f51424dcf4cbbbfa6d4864f0977ad":{
      "scriptId":"u85"},
    "04071a70cb7843a79e7d010019bfaaea":{
      "scriptId":"u86"},
    "3806ed365e48424984331cb1f264ca0f":{
      "scriptId":"u87"},
    "db7b2e1902314afe8758b02dbac169c5":{
      "scriptId":"u88"},
    "5dbc6ff5dc5a4cda8e0069bf64379427":{
      "scriptId":"u89"},
    "8912c216494940b7b1446a971b25dfa5":{
      "scriptId":"u90"},
    "2376b9ea5a1b4e1da1188c0ba80dcca1":{
      "scriptId":"u91"},
    "ced65bd41e1f45e68e464412be00424e":{
      "scriptId":"u92"}}});