//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLMExchange.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrivateResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivateResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLMExchange.Properties.PrivateResource", typeof(PrivateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете отправить только один запрос на пополнение my crypt.
        /// </summary>
        public static string AddMyCrypt__AlreadySended_Description {
            get {
                return ResourceManager.GetString("AddMyCrypt__AlreadySended_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительная информация по запросу.
        /// </summary>
        public static string AddMyCrypt__RequestAdditionalInfo {
            get {
                return ResourceManager.GetString("AddMyCrypt__RequestAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос на пополнение my crypt уже отправлен.
        /// </summary>
        public static string AddMyCrypt_AlreadySended_H1 {
            get {
                return ResourceManager.GetString("AddMyCrypt_AlreadySended_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество запрашиваемых my-crypt.
        /// </summary>
        public static string AddMyCryptConfirmAmpount {
            get {
                return ResourceManager.GetString("AddMyCryptConfirmAmpount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to картинка подтверждающая добавление my-crypt.
        /// </summary>
        public static string AddMyCryptConfirmationImage {
            get {
                return ResourceManager.GetString("AddMyCryptConfirmationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициатор запроса на добавление my-crypt.
        /// </summary>
        public static string AddMyCryptInitiatorPhoto {
            get {
                return ResourceManager.GetString("AddMyCryptInitiatorPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История запросов покупки my-crypt.
        /// </summary>
        public static string BuyingMyCryptRequestHistory {
            get {
                return ResourceManager.GetString("BuyingMyCryptRequestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрана платежная система по умолчанию.
        /// </summary>
        public static string DefaultPaymentSystemNotSet {
            get {
                return ResourceManager.GetString("DefaultPaymentSystemNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система уже выбрана как дефолтная.
        /// </summary>
        public static string Exception_SystemAlreadyDefault {
            get {
                return ResourceManager.GetString("Exception_SystemAlreadyDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть торговую сессию?.
        /// </summary>
        public static string IsTradingSessionShouldBeOpen {
            get {
                return ResourceManager.GetString("IsTradingSessionShouldBeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои рефералы.
        /// </summary>
        public static string MyReferals {
            get {
                return ResourceManager.GetString("MyReferals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо внести проверочный платеж в размере {0}.
        /// </summary>
        public static string NeedCheckPayment {
            get {
                return ResourceManager.GetString("NeedCheckPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платеж подтвержден.
        /// </summary>
        public static string PaymentApproved {
            get {
                return ResourceManager.GetString("PaymentApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платеж не подтвержден.
        /// </summary>
        public static string PaymentNotApproved {
            get {
                return ResourceManager.GetString("PaymentNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплатить.
        /// </summary>
        public static string PaySellerInterestRatePayment {
            get {
                return ResourceManager.GetString("PaySellerInterestRatePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата доходности торговой сессии.
        /// </summary>
        public static string PayYieldTradingSession {
            get {
                return ResourceManager.GetString("PayYieldTradingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая прибыль со всех рефералов.
        /// </summary>
        public static string ProfitFromAllReferals {
            get {
                return ResourceManager.GetString("ProfitFromAllReferals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициатор запроса.
        /// </summary>
        public static string RequestUser {
            get {
                return ResourceManager.GetString("RequestUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо оплатить стоимость МС продавцу согласно котировки 1 к {0}, в размере {1} руб..
        /// </summary>
        public static string RequirePayInterestRateToSaller {
            get {
                return ResourceManager.GetString("RequirePayInterestRateToSaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете закрыть торговую сессию.
        /// </summary>
        public static string TradingSession__CanCloseTradingSession {
            get {
                return ResourceManager.GetString("TradingSession__CanCloseTradingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставшееся количество денег, которое необходимо выставить покупателям, для удовлетворения текущей прибыли по сесии.
        /// </summary>
        public static string TradingSession__RemainingProfitMoneyTotalCount {
            get {
                return ResourceManager.GetString("TradingSession__RemainingProfitMoneyTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно закрыть сессию, скорее всего время ожидания торговой сессии не истекло.
        /// </summary>
        public static string TradingSession_Close__CantClose {
            get {
                return ResourceManager.GetString("TradingSession_Close__CantClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Торговая сессия не открыта.
        /// </summary>
        public static string TradingSessionNotOpened {
            get {
                return ResourceManager.GetString("TradingSessionNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неподтвержденные заявки на пополнение my-crypt.
        /// </summary>
        public static string UnApprovedTransactionList {
            get {
                return ResourceManager.GetString("UnApprovedTransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос уже существует.
        /// </summary>
        public static string UserController__AddMyCrypt_AlreadySended_Title {
            get {
                return ResourceManager.GetString("UserController__AddMyCrypt_AlreadySended_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление пользователями.
        /// </summary>
        public static string UserManagment {
            get {
                return ResourceManager.GetString("UserManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание проверочного платежа системе.
        /// </summary>
        public static string WaitingCheckPayment {
            get {
                return ResourceManager.GetString("WaitingCheckPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание оплаты от покупателя.
        /// </summary>
        public static string WaitingSellerInterestRatePayment {
            get {
                return ResourceManager.GetString("WaitingSellerInterestRatePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание подтверждения оплаты продавцом.
        /// </summary>
        public static string WaitingSellerInterestRatePayment_Accept {
            get {
                return ResourceManager.GetString("WaitingSellerInterestRatePayment_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание закрытия торговой сессии.
        /// </summary>
        public static string WaitingTradingSessionProgress {
            get {
                return ResourceManager.GetString("WaitingTradingSessionProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание заявки на покупку.
        /// </summary>
        public static string WaitingUserResponse {
            get {
                return ResourceManager.GetString("WaitingUserResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание подтверждения платежа.
        /// </summary>
        public static string YieldSessionBill__WaitingForConfirmation {
            get {
                return ResourceManager.GetString("YieldSessionBill__WaitingForConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В текущее время вы не можете покупать MC. Т.к. уже открыта торговая сессия..
        /// </summary>
        public static string YouCantBuyMCNow {
            get {
                return ResourceManager.GetString("YouCantBuyMCNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В текущее время вы не можете продавать MC. Т.к. уже открыта торговая сессия..
        /// </summary>
        public static string YouCantSellMCNow {
            get {
                return ResourceManager.GetString("YouCantSellMCNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш текущий балас my-crypt.
        /// </summary>
        public static string YourCurrentMyCryptBalance {
            get {
                return ResourceManager.GetString("YourCurrentMyCryptBalance", resourceCulture);
            }
        }
    }
}
