//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLMExchange.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLMExchange.Properties.ResourcesA", typeof(ResourcesA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принять.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ к контроллеру (страница, объект и  т.д.).
        /// </summary>
        public static string Action_AccessToController {
            get {
                return ResourceManager.GetString("Action_AccessToController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить My Crypt.
        /// </summary>
        public static string AddMyCrypt {
            get {
                return ResourceManager.GetString("AddMyCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примите соглашение.
        /// </summary>
        public static string AddMyCrypt__TermsAgreed {
            get {
                return ResourceManager.GetString("AddMyCrypt__TermsAgreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос на добавление my crypt в размере {0} отправлен.
        /// </summary>
        public static string AddMyCryptSuccess {
            get {
                return ResourceManager.GetString("AddMyCryptSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление объекта.
        /// </summary>
        public static string AddObject {
            get {
                return ResourceManager.GetString("AddObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавьте фотографию.
        /// </summary>
        public static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить роль.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим администратора.
        /// </summary>
        public static string AdministartorMode {
            get {
                return ResourceManager.GetString("AdministartorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С условиями согласен.
        /// </summary>
        public static string AgreeWithTerms {
            get {
                return ResourceManager.GetString("AgreeWithTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка системы.
        /// </summary>
        public static string ApplicationExceptionOccupied {
            get {
                return ResourceManager.GetString("ApplicationExceptionOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидает подтверждения.
        /// </summary>
        public static string AwaitingConfirm {
            get {
                return ResourceManager.GetString("AwaitingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платеж банка.
        /// </summary>
        public static string BankPayment {
            get {
                return ResourceManager.GetString("BankPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможность подачи заявки на участие в торгах временно ограничена.
        /// </summary>
        public static string BiddingParticipateApplication_IsBanned {
            get {
                return ResourceManager.GetString("BiddingParticipateApplication_IsBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id родителя реферала.
        /// </summary>
        public static string BindReferalUserId {
            get {
                return ResourceManager.GetString("BindReferalUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id пользователя, по отношению к которому стать рефералом.
        /// </summary>
        public static string BindReferalUserIdDescription {
            get {
                return ResourceManager.GetString("BindReferalUserIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить прибыль.
        /// </summary>
        public static string Button_GetProfit {
            get {
                return ResourceManager.GetString("Button_GetProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string Button_Open {
            get {
                return ResourceManager.GetString("Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить.
        /// </summary>
        public static string Button_UpdateMyCrypt {
            get {
                return ResourceManager.GetString("Button_UpdateMyCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупка My Crypt.
        /// </summary>
        public static string BuyMyCrypt {
            get {
                return ResourceManager.GetString("BuyMyCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрещено удалять роль типа &quot;Роль администратора&quot;.
        /// </summary>
        public static string CanNotRemoveAdministratorRolFromUser {
            get {
                return ResourceManager.GetString("CanNotRemoveAdministratorRolFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментариев нет.
        /// </summary>
        public static string Comment_Empty {
            get {
                return ResourceManager.GetString("Comment_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите продолжить действие {0} ?.
        /// </summary>
        public static string ConfirmActionMessage {
            get {
                return ResourceManager.GetString("ConfirmActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите действие.
        /// </summary>
        public static string ConfirmActionTitle {
            get {
                return ResourceManager.GetString("ConfirmActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильно указан код подтверждения.
        /// </summary>
        public static string ConfirmationCodeIncorrect {
            get {
                return ResourceManager.GetString("ConfirmationCodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рынок.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копирайт.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id текущего пользователя.
        /// </summary>
        public static string CurrentUserId {
            get {
                return ResourceManager.GetString("CurrentUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных.
        /// </summary>
        public static string DataEmpty {
            get {
                return ResourceManager.GetString("DataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дефолтная платежная система не задана.
        /// </summary>
        public static string DefaultPaymentSystemNotSet {
            get {
                return ResourceManager.GetString("DefaultPaymentSystemNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дефолтная система.
        /// </summary>
        public static string DefaultSystem {
            get {
                return ResourceManager.GetString("DefaultSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отклонить.
        /// </summary>
        public static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование объекта.
        /// </summary>
        public static string EditObject {
            get {
                return ResourceManager.GetString("EditObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование пользователя.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронный платёж.
        /// </summary>
        public static string ElectronicPayment {
            get {
                return ResourceManager.GetString("ElectronicPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string EnterButton {
            get {
                return ResourceManager.GetString("EnterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите комментарий.
        /// </summary>
        public static string EnterComment {
            get {
                return ResourceManager.GetString("EnterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите логин.
        /// </summary>
        public static string EnterLogin {
            get {
                return ResourceManager.GetString("EnterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите текст сообщения.
        /// </summary>
        public static string EnterMessageText {
            get {
                return ResourceManager.GetString("EnterMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите количество единиц my-crypt.
        /// </summary>
        public static string EnterMyCryptCount {
            get {
                return ResourceManager.GetString("EnterMyCryptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите подтверждение пароля.
        /// </summary>
        public static string EnterPasswordConfirmation {
            get {
                return ResourceManager.GetString("EnterPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите отчество.
        /// </summary>
        public static string EnterPatronymic {
            get {
                return ResourceManager.GetString("EnterPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер телефона.
        /// </summary>
        public static string EnterPhoneNumber {
            get {
                return ResourceManager.GetString("EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тел. номер. Пример +[  7] (916) 123-45-67.
        /// </summary>
        public static string EnterPhoneNumberAsMasked {
            get {
                return ResourceManager.GetString("EnterPhoneNumberAsMasked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер мобильного телефона. Формат ввода +[код региона] (999) 999-99-99. Код региона может быть задан от одной до трех цифр. Пример ввода: +[383] (999) 123-45-67, +[_83] (999) 123-45-67, +[  7] (999) 123-45-67. При вводе кода на место пустых цифр можно вводить либо пробел, либо _..
        /// </summary>
        public static string EnterPhoneNumberAsMaskedDescription {
            get {
                return ResourceManager.GetString("EnterPhoneNumberAsMaskedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Skype-логин.
        /// </summary>
        public static string EnterSkype {
            get {
                return ResourceManager.GetString("EnterSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите фамилию.
        /// </summary>
        public static string EnterSurname {
            get {
                return ResourceManager.GetString("EnterSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите заголовок.
        /// </summary>
        public static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог ошибки.
        /// </summary>
        public static string ErrorLog {
            get {
                return ResourceManager.GetString("ErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный url поддерживает только укороченные запросы (Ajax).
        /// </summary>
        public static string Exception_ActionAjaxOnly {
            get {
                return ResourceManager.GetString("Exception_ActionAjaxOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка приложения.
        /// </summary>
        public static string Exception_ApplicationException {
            get {
                return ResourceManager.GetString("Exception_ApplicationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данная пара Логин - Пароль не найдены.
        /// </summary>
        public static string Exception_LoginFaield {
            get {
                return ResourceManager.GetString("Exception_LoginFaield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель заполнена не верно.
        /// </summary>
        public static string Exception_ModelInvalid {
            get {
                return ResourceManager.GetString("Exception_ModelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не правильно задан параметр {0}.
        /// </summary>
        public static string Exception_WrongParameter {
            get {
                return ResourceManager.GetString("Exception_WrongParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Биржа.
        /// </summary>
        public static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопросы.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее количество символов 10.
        /// </summary>
        public static string FieldCharCountNotRequired_10 {
            get {
                return ResourceManager.GetString("FieldCharCountNotRequired_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее количество символов 20.
        /// </summary>
        public static string FieldCharCountNotRequired_20 {
            get {
                return ResourceManager.GetString("FieldCharCountNotRequired_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее количество символов 9.
        /// </summary>
        public static string FieldCharCountNotRequired_9 {
            get {
                return ResourceManager.GetString("FieldCharCountNotRequired_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильно заполнено поле email.
        /// </summary>
        public static string FieldEmailInvalid {
            get {
                return ResourceManager.GetString("FieldEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле заполнено не верно.
        /// </summary>
        public static string FieldFilledInvalid {
            get {
                return ResourceManager.GetString("FieldFilledInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны выбрать данный пункт.
        /// </summary>
        public static string FieldFilledInvalid_Boolean {
            get {
                return ResourceManager.GetString("FieldFilledInvalid_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы водлжны ввести число.
        /// </summary>
        public static string FieldFilledInvalid_IntegerOnly {
            get {
                return ResourceManager.GetString("FieldFilledInvalid_IntegerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальное количество символов 8.
        /// </summary>
        public static string FieldMinCharCountNotRequired_8 {
            get {
                return ResourceManager.GetString("FieldMinCharCountNotRequired_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальное 16, максимальное 18 символов.
        /// </summary>
        public static string FieldRangeCharCountNotRequired_16_18 {
            get {
                return ResourceManager.GetString("FieldRangeCharCountNotRequired_16_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальное 6 символов, максимальное 20 символов.
        /// </summary>
        public static string FieldRangeCharCountNotRequired_6_20 {
            get {
                return ResourceManager.GetString("FieldRangeCharCountNotRequired_6_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идет загрузка.
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню.
        /// </summary>
        public static string MainMenu__Header {
            get {
                return ResourceManager.GetString("MainMenu__Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать объект по-умолчанию.
        /// </summary>
        public static string MakeObjectDefault {
            get {
                return ResourceManager.GetString("MakeObjectDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вызван метод биндинга для конкретного типа объекта данных: {0}. Тем самым невозможно использовать свойства модели,связанные со свойствами конкретного объекта данных..
        /// </summary>
        public static string Model__Exception_BindNotCall {
            get {
                return ResourceManager.GetString("Model__Exception_BindNotCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрещено изменять поле: {0}.
        /// </summary>
        public static string Model__Exception_PermissionDeniedForFieldChanging {
            get {
                return ResourceManager.GetString("Model__Exception_PermissionDeniedForFieldChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не заполнено.
        /// </summary>
        public static string Model_Exception_FiledIsEmpty {
            get {
                return ResourceManager.GetString("Model_Exception_FiledIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колличество MyCrypt.
        /// </summary>
        public static string MyCryptCount {
            get {
                return ResourceManager.GetString("MyCryptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество my-crypt.
        /// </summary>
        public static string MyCryptNumber {
            get {
                return ResourceManager.GetString("MyCryptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My-Crypt биржа.
        /// </summary>
        public static string MyCryptPage {
            get {
                return ResourceManager.GetString("MyCryptPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определен.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция успешно завершена.
        /// </summary>
        public static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и подтверждение пароля не совпадают.
        /// </summary>
        public static string PasswordDoesnotMatchWithPasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordDoesnotMatchWithPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплатить.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество денег от рефералов.
        /// </summary>
        public static string ProfitMoneyAmount {
            get {
                return ResourceManager.GetString("ProfitMoneyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Случайные мысли.
        /// </summary>
        public static string RandomWords {
            get {
                return ResourceManager.GetString("RandomWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекомендации.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибыль от рефералов.
        /// </summary>
        public static string ReferalProfit {
            get {
                return ResourceManager.GetString("ReferalProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая прибыль от реферала.
        /// </summary>
        public static string RefererProfitTotalCountFromReferal {
            get {
                return ResourceManager.GetString("RefererProfitTotalCountFromReferal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас осталось {0} заявок.
        /// </summary>
        public static string RemaningApplication {
            get {
                return ResourceManager.GetString("RemaningApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продавцы.
        /// </summary>
        public static string SalesPeople {
            get {
                return ResourceManager.GetString("SalesPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя продавца.
        /// </summary>
        public static string SellerName {
            get {
                return ResourceManager.GetString("SellerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия продавца.
        /// </summary>
        public static string SellerSurname {
            get {
                return ResourceManager.GetString("SellerSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть чек.
        /// </summary>
        public static string ShowPayment {
            get {
                return ResourceManager.GetString("ShowPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем, Вы успешно зарегистрированы.
        /// </summary>
        public static string SuccessAccountRegister {
            get {
                return ResourceManager.GetString("SuccessAccountRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше сообщение было успешно отправлено.
        /// </summary>
        public static string SuccessSendMessage {
            get {
                return ResourceManager.GetString("SuccessSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки системы.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно изменить уровень доступа для данной роли.
        /// </summary>
        public static string UpdateAllRoleTypeAccessLevels__Exception_CannotChangeLevel {
            get {
                return ResourceManager.GetString("UpdateAllRoleTypeAccessLevels__Exception_CannotChangeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользовательское соглашение.
        /// </summary>
        public static string UserAgreement {
            get {
                return ResourceManager.GetString("UserAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь уже имеет данный тип роли.
        /// </summary>
        public static string UserAlreadyContainsThisRoleType {
            get {
                return ResourceManager.GetString("UserAlreadyContainsThisRoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышен лимит.
        /// </summary>
        public static string UserBalanceLimit {
            get {
                return ResourceManager.GetString("UserBalanceLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пользователя.
        /// </summary>
        public static string UserConfirmation {
            get {
                return ResourceManager.GetString("UserConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контрольная панель.
        /// </summary>
        public static string UserControlBlock {
            get {
                return ResourceManager.GetString("UserControlBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол. информация.
        /// </summary>
        public static string UserInfo_Short {
            get {
                return ResourceManager.GetString("UserInfo_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким email уже существует.
        /// </summary>
        public static string UserModel__Exception_EmailExists {
            get {
                return ResourceManager.GetString("UserModel__Exception_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильно заполнен телефонный номер.
        /// </summary>
        public static string UserModel__Exception_FieldPhoneNumberInvalid {
            get {
                return ResourceManager.GetString("UserModel__Exception_FieldPhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким логином уже существует.
        /// </summary>
        public static string UserModel__Exception_LoginExists {
            get {
                return ResourceManager.GetString("UserModel__Exception_LoginExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким номером телефона уже существует.
        /// </summary>
        public static string UserModel__Exception_PhoneNumberExists {
            get {
                return ResourceManager.GetString("UserModel__Exception_PhoneNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким скайпом уже существует.
        /// </summary>
        public static string UserModel__Exception_SkypeExists {
            get {
                return ResourceManager.GetString("UserModel__Exception_SkypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильно заполнен Skype-логин.
        /// </summary>
        public static string UserModel__Exception_SkypeInvalid {
            get {
                return ResourceManager.GetString("UserModel__Exception_SkypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотография пользователя.
        /// </summary>
        public static string UserPhoto {
            get {
                return ResourceManager.GetString("UserPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация пользователя.
        /// </summary>
        public static string UserRegistartion {
            get {
                return ResourceManager.GetString("UserRegistartion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр пользователя.
        /// </summary>
        public static string UserView {
            get {
                return ResourceManager.GetString("UserView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рынок.
        /// </summary>
        public static string Wounds {
            get {
                return ResourceManager.GetString("Wounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На это действие у вас нету соответствующих прав.
        /// </summary>
        public static string YouDontHaveAccessToThisAction {
            get {
                return ResourceManager.GetString("YouDontHaveAccessToThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На {0} у вас нету соответствующих прав.
        /// </summary>
        public static string YouDontHaveAccessToThisAction_WithActionDescription {
            get {
                return ResourceManager.GetString("YouDontHaveAccessToThisAction_WithActionDescription", resourceCulture);
            }
        }
    }
}
